# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Zone-Protect/maven-auto-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
