name: On Release

on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Get version from POM
      id: version
      uses: CptMokoena/maven-get-version-action@1.0.3
    - name: Build
      run: mvn package
    - name: Upload to artifact
      uses: softprops/action-gh-release@v1
      with:
        files: target/zones-${{ steps.version.outputs.version }}.jar
        tag_name: ${{ steps.version.outputs.version }}
        release_name: Zones V${{ steps.version.outputs.version }}
        body: 'Changes coming soon'
        token: ${{secrets.GITHUB_TOKEN}}
        draft: true
        prerelease: true
        fail_on_unmatched_files: true
        
    
      
