# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Maven Release
        uses: eric2788/maven-jar-publish@v1
        with:
          draft: true
        
          
