name: On Release

on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Get version from POM
      id: version
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'pom.xml'
        xpath: '/project/version'
    - name: Create release
      id: release
      uses: actions/create-release@v1
      with: 
        tag_name: ${{ steps.version.outputs.info }}
        release_name: Zones V${{ steps.version.outputs.info }}
        body: 'Changes coming soon'
        draft: true
        prerelease: true
    - name: Build
      run: mvn package
    - name: Upload to artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{steps.release.outputs.upload_url}}
        asset_path: 'target/zones-${{ steps.version.outputs.info }}'
        asset_name: 'Zones.jar'
        asset_content_type: application/java-archive
        
    
      
